configfile: 'config/config.yml'


#need this to make sure iterations don't go below 0!
wildcard_constraints:
    iteration="[0-9]+",


include: 'rules/setup.smk'
# include: 'rules/reg_t2_to_t1.smk'
include: 'rules/initialize_template.smk'
include: 'rules/ants_template.smk'
# include: 'rules/templateflow.smk'
# include: 'rules/cohort_template_to_std.smk'



rule all_composite_warps:
    input:
        expand(
            [
                rules.get_final_xfm.output[0],
                rules.get_final_inv_xfm.output[0],
                rules.get_final_warped.output[0],
            ],
            subject=inputs.subjects,
            template=config['template_name']
        ),
    
    


if config['run_iter'] != None:
    rule all_iter:
        input:
             expand('results/cohort-{cohort}/iter_{iter}/template_{channel}.nii.gz',cohort=cohorts,channel=channels,iter=config['run_iter'])
else:
    rule all_finaltemplate:
        input:
            json = 'results/tpl-{name}/template_description.json'.format(name=config['template_name'])



