#assumes that templateflow templates are linked in resources folder
# init_template:
#   FA: /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/fsl/6.0.4/fsl/data/standard/FMRIB58_FA_1mm.nii.gz

pybids_inputs:
  FA:
    filters:
      suffix: mdp
      desc: FA
      space: T1w
      scope: prepdwi_recon
      datatype: dwi
    wildcards:
    - subject
    - session

pybids_outputs:
  FA:
    suffix: FA.nii.gz

targets_by_analysis_level:
  participant:
  - ''
  group:
  - 'reference_warps'
analysis_levels: &analysis_levels
- group
- participant

parse_args:
  bids_dir:
    help: |
      The directory with the input dataset formatted according to the BIDS
      standard.
  output_dir:
    help: |
      The directory where the output files should be stored. If you are running
      group level analysis this folder should be prepopulated with the results
      of the participant level analysis.
  analysis_level:
    help: Level of the analysis that will be performed.
    choices: *analysis_levels
  --participant_label:
    help: |
      The label(s) of the participant(s) that should be analyzed. The label
      corresponds to sub-<participant_label> from the BIDS spec (so it does not
      include "sub-"). If this parameter is not provided all subjects should be
      analyzed. Multiple participants can be specified with a space separated
      list.
    nargs: +
  --exclude_participant_label:
    help: |
      The label(s) of the participant(s) that should be excluded. The label
      corresponds to sub-<participant_label> from the BIDS spec (so it does not
      include "sub-"). If this parameter is not provided all subjects should be
      analyzed. Multiple participants can be specified with a space separated
      list.
    nargs: +
  --derivatives:
    help: Index derivative datasets found with <bids_dir>/derivatives
    action: store_true
    default: false
  --template_name:
    help: Name for final template (will appear in output as tpl-<template_name>)
    default: study
  --num_iters:
    help: Number of registration iterations to run
    default: "8"
  --workdir:
    help: |
      Directory to store temporary outputs. Defaults to the snakemake 
      default-resources tmpdir, or if that's unset, a platform-specific tmpdir.
      (Note, this option must be explicitly set to resume an interrupted
      workflow.)
    default: ''
  --reference-templates:
    help: |
      Transforms to and from the derived template will be calculated for all
      templates listed here in group mode. Values must be valid `tpl` keys from
      `templateflow`
    default:
      - MNI152NLin6Asym
    nargs: "+"





resolution_index: 1 # res-{resolution_index}
#shape, zooms, origin will be obtained from the nifti itself


#for creating the template_description.json file
template_description_extras:
  Name: 'Brief template description goes here'
  Authors:
    - 'Your Name Here'
  Acknowledgements: 'Created by ants_build_template_smk Snakemake workflow'
  BIDSVersion:
    - '1.1.0' 
  License: 'See LICENSE file'
  TemplateFlowVersion: '1.0.0'



#will register cohort templates to the std template after they are generated
std_template_name: 'MNI152NLin6Asym'

#keep this empty, is set by command-line ( --config run_iter=1 or --config run_cohort=young)
run_cohort: 
run_iter: 

init_template:
  FA: /scratch/knavynde/jhp/derivatives/tpl-incl/tpl-study/tpl-study_FA.nii.gz



resample_init_template: False #set this True to resample init template to below dims 
# WARNING - changing this can significantly alter memory usage and run-time -- 
resample_vox_dims: 
 - 1
 - 1
 - 1



#should be at least 2.3.4 (includes --random-seed option, and fixes some argparsing bugs)
singularity:
  prepdwi: '/project/6050199/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif'  
  ants:  '/project/6050199/akhanf/singularity/kaczmarj_ants_2.3.4.sif'
  itksnap:  '/project/6050199/akhanf/singularity/pyushkevich_itksnap_latest.sif'
  python: 'docker://khanlab/pythondeps-snakedwi:v0.2.0'

ants:
  dim: 3
  shape_update:
      gradient_step: 0.25



